[project]
name = "managing-subscriptions-tbank"
version = "0.1.0"
description = "Subscription management service — T-Bank hackathon"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2",
    "numpy>=1.26",
    "faker>=24.0",
    "lightgbm>=4.3",
    "scikit-learn>=1.4",
    "joblib>=1.3",
    "fastapi>=0.111",
    "uvicorn[standard]>=0.29",
    "sqlalchemy>=2.0",
    "pydantic>=2.0",
]

[tool.uv]
dev-dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
